### ISSUE TITLE
Create a way to identify when objects have OCR

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/content_search#47]
Per DEVQUEUE-196, we need to define and implement the data model changes for image-based resources (`image` and `page` types) necessary to identify when objects have OCR. This may include `<bookData>` OCR declaration and could reinstate an optional format attribute on files to supplement the mimetype.

This information is then used to determine when the search service stanza is included in the manifest for the object.

**Analysis**

Identify supported formats of OCR, as well as the full landscape of what we have. `content_search` currently indexes ALTO3, ALTO2, and plain text, but since we're making data model changes we need to know what's out there.

**Questions**

* Can we identify the `type` in `contentMetadata` that  we need to support? 
* `content_search` currently supports `page` resource types only, but what `image`s exist with OCR?

**Comment by LynnMcRae** [comment]
Chatted with Chris. The idea of a `<bookData>` tag at the top of contentMetadata was to provide a hint that the object was prepared with OCR if optimizing that fact for the viewer was useful (to avoid file level scanning). But that could be done once in the preparation of the manifest rather than pre-cast in contentMetadata. We looked at a "role" attribute for `<file>` as a possible way of flagging OCR/transcript. That attribute was suggested long ago as a possible way of distinguishing, say, "master" from "derivative" from "cropped" etc. if needed, but it was never implemented.

**Comment by cbeer** [comment]
(@LynnMcRae beat me by seconds, but:)

I believe we're thinking about adding a `role="transcription"` attribute to the `<file>` element that references the OCR'ed (or manually transcribed, or speech-to-text'ed, etc) content. The `@role` attribute was never implemented, but was initially described as:

> Possible attribute to distinguish like files in a resource where a published resource wants alternate representations, e.f., cropped/uncropped for a single resource.

Other options considered include:

- A top-level declaration like `<bookData>` seems insufficient to accurately identify the presence of OCR data files without a lot of additional heuristics;
- trying to key content search behavior off of the mime type risks false (or burdensome) identification of content
