### ISSUE TITLE
Investigate why UV shows "page 4 -" and does not have the total number

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/content_search#6]

**Comment by aeschylus** [comment]
This [PR](https://github.com/sul-dlss/universalviewer/pull/48) addresses https://github.com/sul-dlss/content_search/issues/6 in DLSS content_search. The changes eliminate logic that used to handle paged and unpaged objects differently. This seems reasonable because of the use of the construct "image/page [n] _of_ [m]" as a design choice. Canvas labels often don't describe order in any way [[cit.](http://iiif.io/api/presentation/2.1/#label)], leading to examples such as "page Homily of March of Appendices", which doesn't make much sense.

The Presentation API doesn't provide a way to have a "logical page number" and "digital page (IIIF "Canvas") number or "sequence index" apart from labels, which can have any content whatsoever, so I'm not sure what a better design choice might be here. In the meantime, this uses data that is always available (the number of canvases, regardless of viewingHint) to give an idea of the relative position of the currently focuses canvas in the sequence. I think the spec lacks the data to do better than that for now.

**Comment by aeschylus** [comment]
@anarchivist Yes, I think this is a problem with the function that extracts labels, which doesn't exist in the PR, but it is also worth noting. I'll ticket that for UV/UV as well.

**Comment by anarchivist** [comment]
see UniversalViewer/universalviewer#531 - what was the outcome of the discussion?
