### ISSUE TITLE
Investigate ICU support

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/content_search#7]

**Comment by cbeer** [comment]
Using the `ICUTokenizer` directly almost certainly won't work. Fortunately, I believe this is only a problem for non-ALTO OCR ("text per page"), as the OCR we get back should be pre-tokenized with word positions. 

@ndushay suggested if we need to use Solr's ICUTokenizer to extract words, we could use it directly (through the Solr Analysis API, or otherwise) and continue to use the WhitespaceTokenizer with our payload.

One other thing that occurred to me is we could use two different fields (one with our payload and whitespace tokenized, one with the icutokenizer without payload), but it may be interesting to try to merge the highlighting results.
